"""Professional PDF audit report for Ledger Sentinel.

Generates a one-page+ audit report with cover, KPIs, exception table,
and sign-off line. Uses fpdf2 (lightweight, no system deps).

Usage:
    from app.report import build_pdf
    pdf_bytes = build_pdf(audit_df, recon_df_summary)

Also callable as script:
    python -m app.report
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def _safe(text: str, limit: int = 500) -> str:
    if text is None:
        return "-"
    s = str(text).replace("\x00", "")
    # sanitize unicode that core fonts can't handle
    s = s.replace("\u2014", "-").replace("\u2013", "-").replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"').replace("\u2022", "-")
    s = s.encode("latin-1", errors="replace").decode("latin-1")
    if len(s) > limit:
        s = s[: limit - 3] + "..."
    return s


def build_pdf(audit_df: pd.DataFrame, summary: dict | None = None, title: str = "Ledger Sentinel - Audit Report") -> bytes:
    from fpdf import FPDF

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(120, 120, 130)
            self.cell(0, 6, "LEDGER SENTINEL  |  Razorpay AI Finance Controller", align="L")
            self.set_font("Helvetica", "", 8)
            self.cell(0, 6, datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), align="R", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(200, 200, 210)
            self.line(10, 13, 200, 13)
            self.ln(2)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "", 7)
            self.set_text_color(140, 140, 150)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Confidential - generated by Ledger Sentinel", align="C")

    pdf = PDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(0, 6, "Reconciliation audit trail  -  every row accounted for, every exception explained.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # KPIs
    if summary is None:
        recon = audit_df[audit_df["outcome"].isin(["matched", "exception"])] if not audit_df.empty else audit_df
        matched = int((recon["outcome"] == "matched").sum()) if not recon.empty else 0
        exceptions = int((recon["outcome"] == "exception").sum()) if not recon.empty else 0
        total = matched + exceptions
        rate = round(matched / total * 100, 1) if total else 0.0
        by_reason = recon["reason"].value_counts().to_dict() if not recon.empty and "reason" in recon.columns else {}
        summary = {"total_rows": total, "matched": matched, "exceptions": exceptions, "match_rate_pct": rate, "by_reason": by_reason}

    # KPI cards as table
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(51, 65, 85)
    cols = [("Total rows", str(summary.get("total_rows", 0))), ("Matched", str(summary.get("matched", 0))), ("Exceptions", str(summary.get("exceptions", 0))), ("Match rate", f"{summary.get('match_rate_pct', 0)}%")]
    w = 190 / 4
    for label, _ in cols:
        pdf.cell(w, 7, label, border=1, align="C", fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(15, 23, 42)
    for _, val in cols:
        pdf.cell(w, 10, val, border=1, align="C")
    pdf.ln(12)

    # By reason
    by_reason = summary.get("by_reason", {})
    if by_reason:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(0, 6, "Exceptions by reason", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(30, 41, 59)
        for k, v in sorted(by_reason.items()):
            pdf.cell(0, 5, f"  - {k}: {v}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # Exception table
    exc = audit_df[audit_df["outcome"] == "exception"].copy() if not audit_df.empty and "outcome" in audit_df.columns else pd.DataFrame()
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 7, f"Exception detail  ({len(exc)} rows)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    if exc.empty:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(34, 139, 34)
        pdf.cell(0, 6, "No exceptions — everything reconciled.", new_x="LMARGIN", new_y="NEXT")
    else:
        # Table header
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_fill_color(15, 23, 42)
        pdf.set_text_color(255, 255, 255)
        col_widths = [28, 32, 34, 96]
        headers = ["Order", "Reason", "Classification", "Audit note"]
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 7, h, border=1, align="C", fill=True)
        pdf.ln()
        pdf.set_font("Helvetica", "", 6.5)
        pdf.set_text_color(30, 30, 30)
        for _, r in exc.head(60).iterrows():
            # row height based on note length
            note = _safe(r.get("audit_note", ""), 220)
            # simple: fixed height, truncate
            cells = [_safe(r.get("order_id", "")), _safe(r.get("reason", ""), 28), _safe(r.get("classification", ""), 28), note]
            h = 6
            # need to handle multi-line note: use multi_cell for last col is messy in row layout
            # so we do cell with truncated single line
            x = pdf.get_x()
            y = pdf.get_y()
            if y > 275:
                pdf.add_page()
            for i, c in enumerate(cells):
                pdf.cell(col_widths[i], h, c[: 52 if i == 3 else 22], border=1)
            pdf.ln()
        if len(exc) > 60:
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 5, f"... and {len(exc)-60} more rows (see CSV export for full data)", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)
    # Money at risk
    try:
        if not exc.empty and "amount" in exc.columns:
            # estimate at-risk as sum of diff where available
            at_risk = exc["diff"].abs().sum() if "diff" in exc.columns else 0
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(0, 5, f"Estimated amount in exceptions: Rs {at_risk:,.2f}" if at_risk else "", new_x="LMARGIN", new_y="NEXT")
    except Exception:
        pass

    pdf.ln(4)
    pdf.set_draw_color(200, 200, 210)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 4, "Sign-off:  ___________________________          Date:  _______________\nFinance Controller  -  I have reviewed the exceptions above and confirm follow-up actions.")
    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(140, 140, 150)
    pdf.cell(0, 4, "Generated by Ledger Sentinel. Deterministic matching first, AI explanation only on exceptions. Every row is auditable.", new_x="LMARGIN", new_y="NEXT")

    out = io.BytesIO()
    pdf.output(out)
    return out.getvalue()


if __name__ == "__main__":
    from app import db
    from app.config import db_path

    p = Path(db_path())
    if not p.exists():
        print(f"No DB at {p}, run python -m app.main first")
        raise SystemExit(1)
    conn = db.get_connection(str(p))
    audit = db.load_audit_df(conn)
    conn.close()
    pdf_bytes = build_pdf(audit)
    out_path = Path("audit_report.pdf")
    out_path.write_bytes(pdf_bytes)
    print(f"Wrote {out_path} ({len(pdf_bytes)} bytes)")
